version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running pre-build steps"
      - flake8 ../src/ tests/
      - black --check ../src/ ../tests/
  build:
    commands:
      - echo "Running PySpark job"
      - pytest --cov=../src/ ../tests
      - python src/data_ingestion/ingest_data.py
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'